# Generated by Django 4.0.1 on 2022-01-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_desgination',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='projects',
            new_name='project',
        ),
    ]
